apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: {{ include "chart.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{ include "chart.labels" . | nindent 4 }}
data: 
  dnsmasq.conf: |-
    {{ .Values.config.data | nindent 4 }}
