apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dns-a
  namespace: argocd
  labels:
    app: dns-a
spec:
  project: prod
  source:
    repoURL: 'https://github.com/thrv-prod/repo.git'
    path: dnsmasq
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - ci/prod-values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
