replicaCount: 1
image: 
  repository: alpine 
  tag: 3.19
service: 
  port: 53
  type: LoadBalancer
namespace: prod
ingress:
  enabled: no
  host: corp.local
  privateIssuer: lab-ca-issuer
  # set issuer for signing certs
  tls: 
    enabled: false
persistence: 
  enabled: true
  storageClassName: ssd
  size: 75Mi
resources:
  requests: 
    memory: "50Mi"
    cpu: "100m"
  limits: 
    memory: "150Mi"
    cpu: "250m"
config: 
  data: |
    bogus-priv
    domain-needed
    cache-size=1000
    log-queries
    log-facility=/var/log/dnsmasq.log
    address=/corp.local/100.30.30.10
